name: Sync Fork

on:
  schedule:
    - cron: '11 3 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: terminussync/fork-sync@master
        with:
          owner: SnapDrop
          base: master
          head: master
